name: Recon Shell Scripts CI

on:
  push:
    paths:
      - 'recon/*.sh'
  pull_request:
    paths:
      - 'recon/*.sh'

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install ShellCheck
        run: sudo apt-get update && sudo apt-get install -y shellcheck
      - name: Lint all shell scripts
        run: shellcheck recon/*.sh
      - name: Check script syntax
        run: |
          for f in recon/*.sh; do
            bash -n "$f"
          done
